language: objective-c
osx_image: xcode9.4
xcode_project: ./iOS/CleanArchitecture.xcodeproj # path to your xcodeproj folder
xcode_scheme: CleanArchitecture
xcode_destination: platform=iOS Simulator,OS=11.4.1,name=iPhone X

